#
# Copyright 2024 Adobe. All rights reserved.
# This file is licensed to you under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License. You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under
# the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
# OF ANY KIND, either express or implied. See the License for the specific language
# governing permissions and limitations under the License.
#

name: Build and Test (Android)

on:
  workflow_call:
    inputs:
      android-api-levels:
        description: |
          The Android API levels to use for testing. Must be formatted as a valid JSON array string.
          Example: '[29, 30]'
            - Notice the use of single quotes to wrap the JSON array string, and number format for values.
        type: string
        default: '[29]'
      # Flags for which tests to run
      run-test-unit:
        type: boolean
        default: false
      run-test-functional:
        type: boolean
        default: false
      run-test-integration:
        type: boolean
        default: false
      run-build-app:
        type: boolean
        default: false
      enable-codecov:
        description: 'Enable Codecov for test coverage.'
        type: boolean
        default: false
      javadoc-build-path:
        description: |
          The build path where Javadoc files are stored (ex: code/edgeidentity/build/dokka/javadoc).
          If a value is not provided, the Javadoc job will be skipped.
        type: string
        default: ''

jobs:
  validate-code:
    name: Validate Code
    uses: adobe/aepsdk-commons/.github/workflows/android-validate-code.yml@gha-android-3.1.1
  
  javadoc:
    name: Javadoc
    needs: validate-code
    uses: adobe/aepsdk-commons/.github/workflows/android-javadoc.yml@gha-android-3.1.1
    with:
      javadoc-build-path: ${{ inputs.javadoc-build-path }}
    
  test-unit:
    name: Unit Test
    needs: validate-code
    if: inputs.run-test-unit
    uses: adobe/aepsdk-commons/.github/workflows/android-custom-command-build-and-test.yml@gha-android-3.1.1
    with:
      android-api-levels: ${{ inputs.android-api-levels }}
      command: make unit-test-coverage
      enable-codecov: ${{ inputs.enable-codecov }}
      codecov-flag: android-unit-tests
    secrets: inherit

  test-functional:
    name: Functional Test
    needs: validate-code
    if: inputs.run-test-functional
    uses: adobe/aepsdk-commons/.github/workflows/android-custom-command-build-and-test.yml@gha-android-3.1.1
    with:
      android-api-levels: ${{ inputs.android-api-levels }}
      command: make functional-test-coverage
      enable-codecov: ${{ inputs.enable-codecov }}
      codecov-flag: android-functional-tests
    secrets: inherit

  test-integration:
    name: Integration Test
    needs: validate-code
    if: inputs.run-test-integration
    uses: adobe/aepsdk-commons/.github/workflows/android-custom-command-build-and-test.yml@gha-android-3.1.1
    with:
      android-api-levels: ${{ inputs.android-api-levels }}
      command: make integration-test-coverage
      enable-codecov: ${{ inputs.enable-codecov }}
      codecov-flag: android-integration-tests
    secrets: inherit

  build-app:
    name: Build Test App
    runs-on: ubuntu-24.04
    needs: validate-code
    if: inputs.run-build-app

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
      
      - name: Setup Dependencies
        uses: adobe/aepsdk-commons/.github/actions/android-setup-dependencies-action@gha-android-3.1.1

      - name: Assemble App
        run: make assemble-app